### ISSUE TITLE
could u pls share the slide to me?

### ISSUE THREAD

**Issue by michaelcjl** [DataXujing/TensorRT-LLM-ChatGLM3#2]

**Comment by DataXujing** [comment]
稍后会把slide提交到repo

**Comment by daocunyang** [comment]
+1

**Comment by DataXujing** [comment]
关于本repo涉及的slide已经更新提交，请参考： <https://github.com/DataXujing/TensorRT-LLM-ChatGLM3/blob/main/Triton%E5%A4%A7%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2.pdf>
